# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust

matrix:
  include:
    # integration tests with rust-cookbook
    - os: linux
      rust: stable
      env: INTEGRATION_TESTS=1

    # skeptic unit tests
    - os: linux
      rust: 1.32.0
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly

before_install: set -e

install:
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

deploy:
  on:
    condition: $DEPLOY = never

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
